### PR TITLE
Chipseq revamp: part 2

### LINKED ISSUE #31: Add multiQC
WIP...

### LINKED ISSUE #36: Ignore chrX for normalization
X chromsome should be excluded for calculation of 1x normalization in bamCoverage..

### LINKED ISSUE #43: salmon --> DESeq
The current master branch is not handling salmon output correctly for DESeq. It simply converts gene counts from floats to integers.. TxImport needs to be implemented using `tx2gene` annotation and `quant.sf` files.

This step is currently broken the develop branch.

### LINKED ISSUE #47: change the bamCompare output suffix
The suffix says `filtered.subtract.input.bw` and `filtered.log2ratio.over_input.bw` for the two bamCompare commands. But the `control` sample doesn't have to be INPUT. In my example I have both Input and H3 controls and If I re-run with H3 control the Input subtracted files would be either over-written or not produced.

### LINKED ISSUE #48: ChIP-Seq : keep only uniquely mapping reads by default
In the bam filtering rule, only uniquely mapping reads should be kept by default, we can specify a flag to count the multimappers if users wish to..

### PR DESCRIPTION
**Pull request by vivekbhr**
Updates : 
- Moved DB and DE functions to R package **snakediff**.
- Fixed bugs in DB functions.
-  Added multiQC (closes #31 )
- Added X,Y,M and scaffolds for --ignoreForNorm in bamComapre/bamCoverage (closes #36 )
- Modified doc about uniquely mapping reads in DNA mapping (closes #48 )
- Changed bamCompare output suffix (closes #47 )
- modified changeLog
- Fixed Salmon --> DESeq tximport error (closes #43 )

This PR could be merged after these changes:

- [x] Get an issue fixed about output directory in SNPsplit.
- [x] Get SNPsplit installed in /package/ and change `paths.yaml`
- [x] Fix Salmon --> DESeq error.

### CODE REVIEW

**Comment by steffenheyne** [comment]
we can also merge this now into develop and fix the snpsplit issues later in develop

**Comment by vivekbhr** [comment]
@steffenheyne yah ideally, one would install the repository, which would install all the dependencies, all tools along with R packages. At this moment one can still use all functions for snakediff without installing, and install the required R packages using the separate shell thingy that fabian wrote. But in future we would install the workflow which installs all other dependencies as well.

**Comment by vivekbhr** [comment]
closes #43 as well..
I'll update the SNPsplit path tomorrow and remove the WIP..

**Comment by vivekbhr** [comment]
Boom! Ready to merge.. 

Can anyone test these three if possible, on your end?

1. Salmon --> DESeq  : @steffenheyne , you might have some test files already.

2. Differential binding on CSAW  : @mirax87 did you test it already from the pipeline? 

3. Allele-specific DNA mapping : @mirax87 can you test it for your ATAC seq data (only the DNA mapping part) ?

**Comment by vivekbhr** [comment]
There's an issue in running DEseq_basic when the files are allele-specific.. Let me fix that

**Comment by vivekbhr** [comment]
ok.. It works now.. :+1:

**Comment by vivekbhr** [comment]
@steffenheyne ready to merge whenever you want

**Pull request merged**
